services:
  - type: web
    name: roostech-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
