services:
  - type: web
    name: roostechapi
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: DATABASE_URL
        value: mysql+mysqlconnector://root:$hcsr04298N@srv458.hstgr.io/u932627191_roostechdb
